service: serverless

provider:
  name: aws
  region: af-south-1
  runtime: nodejs22.x

  logs:
    restApi: true

functions:
functions:
  resize:
    handler: src/scraper.scrappedDataAdded
    events:
      - s3:
          bucket: scrappy-scrapped
          event: s3:ObjectCreated:*
          existing: true
  scraper:
    handler: src/api/scraper_handler.handler
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    events:
      - http:
          path: api/scraper
          method: post
          request:
            schemas:
              application/json: ${file(src/schema/message_schema.json)}
  expolerUrl:
    handler: src/scraper.exploreUrl
    events:
      - sqs:
          arn: arn:aws:sqs:af-south-1:227299563662:scrappy

plugins:
  - serverless-offline
